# Generated by Django 5.2.2 on 2025-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_location_token_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='token',
        ),
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
