# Generated by Django 5.2.2 on 2025-07-27 14:13

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_location_token_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.booking_photo_upload_path),
        ),
    ]
