# Generated by Django 5.2.2 on 2025-07-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='photo',
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
    ]
